# Generated by Django 5.2 on 2025-05-16 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="כותרת")),
                ("description", models.TextField(verbose_name="תיאור")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="project_images/",
                        verbose_name="תמונה",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="קישור")),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="רשימת טכנולוגיות מופרדת בפסיק",
                        max_length=200,
                        verbose_name="טכנולוגיות",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="מספר נמוך יופיע ראשון",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="סדר תצוגה",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                        verbose_name="ארגון",
                    ),
                ),
            ],
            options={
                "verbose_name": "פרויקט",
                "verbose_name_plural": "פרויקטים",
                "ordering": ["organization", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="כותרת")),
                ("description", models.TextField(verbose_name="תיאור")),
                (
                    "icon_identifier",
                    models.CharField(
                        help_text="לדוגמה: 'fas fa-code' או 'desktop' (לפי FontAwesome)",
                        max_length=100,
                        verbose_name="מזהה אייקון",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="מספר נמוך יופיע ראשון",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="סדר תצוגה",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                        verbose_name="ארגון",
                    ),
                ),
            ],
            options={
                "verbose_name": "שירות",
                "verbose_name_plural": "שירותים",
                "ordering": ["organization", "order", "title"],
            },
        ),
    ]
