# Generated by Django 5.2 on 2025-05-16 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="שם פרטי"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="שם משפחה"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="אימייל"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="מספר טלפון"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="תיאור"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "חדש"),
                            ("contacted", "נוצר קשר"),
                            ("inprogress", "בתהליך"),
                            ("lost", "אבוד"),
                            ("won", "זכיה"),
                        ],
                        default="new",
                        max_length=15,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "נמוכה"),
                            ("medium", "בינונית"),
                            ("high", "גבוהה"),
                        ],
                        default="medium",
                        max_length=15,
                        verbose_name="עדיפות",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="נוצר בתאריך"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="עודכן בתאריך"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="משוייך ל",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נוצר על ידי",
                    ),
                ),
            ],
            options={
                "verbose_name": "ליד",
                "verbose_name_plural": "לידים",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "שיחה טלפונית"),
                            ("meeting", "פגישה"),
                            ("email", "אימייל"),
                            ("chat", "צ'אט"),
                            ("other", "אחר"),
                        ],
                        default="call",
                        max_length=15,
                        verbose_name="סוג אינטראקציה",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="תאריך ושעת אינטראקציה",
                    ),
                ),
                ("notes", models.TextField(verbose_name="סיכום האינטראקציה")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="משך בדקות (אופציונלי)"
                    ),
                ),
                (
                    "next_step_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="הערות לצעד הבא (אופציונלי)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="נציג",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="leads.lead",
                        verbose_name="ליד משויך",
                    ),
                ),
            ],
            options={
                "verbose_name": "יומן אינטראקציה",
                "verbose_name_plural": "יומני אינטראקציות",
                "ordering": ("-timestamp",),
            },
        ),
    ]
